### ISSUE TITLE
Intel Arc support

### ISSUE THREAD

**Issue by itlackey** [microsoft/DeepSpeed-Kernels#13]
Please add support for Intel Arc GPUs via the Intel PyTorch extensions or provide instructions on how to leverage Intel PyTorch.

**Comment by loadams** [comment]
Thanks, @itlackey, we will eventually be adding support for others, but those will be brought into DeepSpeed first, these are additional kernels, you will want to see the progress on the xpu and cpu accelerators in DeepSpeed and open an issue there if you have issues, thanks!
