### ISSUE TITLE
 fatal error: cutlass/gemm/gemm.h: No such file or directory

### ISSUE THREAD

**Issue by 4thGardenOfQMH** [microsoft/DeepSpeed-Kernels#16]
Hi,I want run this repo by setup.py with cmd:
` python setup.py bdist_wheel`

an error occurred,error log:

`
`fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
running bdist_wheel
running build
running build_py
copying dskernels/version.py -> build/lib.linux-x86_64-3.8/dskernels
running egg_info
writing deepspeed_kernels.egg-info/PKG-INFO
writing dependency_links to deepspeed_kernels.egg-info/dependency_links.txt
writing requirements to deepspeed_kernels.egg-info/requires.txt
writing top-level names to deepspeed_kernels.egg-info/top_level.txt
reading manifest file 'deepspeed_kernels.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'dskernels/*.so'
writing manifest file 'deepspeed_kernels.egg-info/SOURCES.txt'
running build_ext
-- Configuring done (0.0s)
-- Generating done (0.5s)
-- Build files have been written to: /mnt/home/qimanhua/DeepSpeed-Kernels-main/build/temp.linux-x86_64-3.8/deepspeed_ft_gemm
[ 12%] Building CXX object CMakeFiles/cutlass_preprocessors.dir/utils/cutlass_preprocessors.cc.o
[ 12%] Building CXX object CMakeFiles/cutlass_heuristic.dir/utils/cutlass_heuristic.cc.o
/mnt/home/qimanhua/DeepSpeed-Kernels-main/dskernels/ft_gemm/gemm_variants/utils/cutlass_heuristic.cc:22:10: fatal error: cutlass/gemm/gemm.h: No such file or directory
   22 | #include "cutlass/gemm/gemm.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Elapsed time: 0 s. (time), 0.000286 s. (clock)
make[2]: *** [CMakeFiles/cutlass_heuristic.dir/build.make:76: CMakeFiles/cutlass_heuristic.dir/utils/cutlass_heuristic.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/cutlass_heuristic.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /mnt/home/qimanhua/DeepSpeed-Kernels-main/dskernels/ft_gemm/gemm_variants/utils/cutlass_preprocessors.cc:21:
/mnt/home/qimanhua/DeepSpeed-Kernels-main/dskernels/ft_gemm/gemm_variants/cutlass_extensions/gemm/kernel/mixed_gemm_B_layout.h:12:10: fatal error: cutlass/layout/matrix.h: No such file or directory
   12 | #include "cutlass/layout/matrix.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Elapsed time: 0 s. (time), 0.000285 s. (clock)
make[2]: *** [CMakeFiles/cutlass_preprocessors.dir/build.make:76: CMakeFiles/cutlass_preprocessors.dir/utils/cutlass_preprocessors.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/cutlass_preprocessors.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 96, in <module>
    setup(name="deepspeed-kernels",
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/home/qimanhua/DeepSpeed-Kernels-main/builder/builder.py", line 60, in run
    self.build_extension(ext)
  File "/mnt/home/qimanhua/DeepSpeed-Kernels-main/builder/builder.py", line 83, in build_extension
    subprocess.check_call(make_cmd.split(" "), cwd=abs_build_temp)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j']' returned non-zero exit status 2.
root@ctmt2312040851156ef-86d775d887-8c2lt:/mnt/home/qimanhua/DeepSpeed-Kernels-main# 
``

**Comment by loadams** [comment]
Hi @4thGardenOfQMH - do you have cutlass installed?  But realistically, to quote from the readme:

> This library is not intended to be an independent user package, but is open-source to benefit the community and show how DeepSpeed is accelerating text-generation.

**Comment by loadams** [comment]
Closing as this is stale.
