### ISSUE TITLE
Please provide release and tag

### ISSUE THREAD

**Issue by ccoulombe** [microsoft/DeepSpeed-Kernels#18]
For reproducibility and being able to distribute DS-kernel, please tag the release. Thanks

**Comment by loadams** [comment]
Hi @ccoulombe - we will get to this shortly, thanks

**Comment by VRehnberg** [comment]
@loadams any update on this?

I think you want to tag this https://github.com/microsoft/DeepSpeed-Kernels/commit/bdb30fdf51bab5053a6a4143823e8cb81d808c2e to 0.1.0 and this https://github.com/microsoft/DeepSpeed-Kernels/commit/f41221e2d2401e0fbcf0ad16b08c21af2154f966 to 0.01.

**Comment by loadams** [comment]
Hi @VRehnberg - thanks for the reminder (even though it took 3 more weeks).  This is done now, I've tagged those commits and they appear visible to me now.  For future releases we will use the release workflow that will do this automatically, but thanks for the reminder.

cc: @ccoulombe (thanks for the original issue)
